export const GET_USER_DATA = 'USER/GET_USER_DATA'
export const GET_POSTS = 'POSTS/GET_POSTS'
export const SET_CURRENT_PAGE = 'POSTS/SET_CURRENT_PAGE'
export const SET_TOTAL_POSTS_COUNT = 'POSTS/SET_TOTAL_POSTS_COUNT'


export const TOGGLE_LIKE = 'POSTS/TOGGLE_LIKE'
export const TOGGLE_LIKE_POST = 'POSTS/TOGGLE_LIKE_POST'

export const GET_POST_BY_ID = 'POST/GET_POST_BY_ID'
export const GET_POSTS_BY_CATEGORY = 'POST/GET_POSTS_BY_CATEGORY'
export const DELETE_POST_BY_ID = 'POST/DELETE_POST_BY_ID'

export const ADD_COMMENT = 'POST/ADD_COMMENT'
export const DELETE_COMMENT = 'POST/DELETE_COMMENT'

export const ADD_POST = 'POSTS/ADD_POST'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'






