export const GET_USER_DATA = 'USER/GET_USER_DATA'

export const GET_POSTS = 'POSTS/GET_POST'
export const TOGGLE_LIKE = 'POSTS/TOGGLE_LIKE'
export const ADD_COMMENT = 'POSTS/ADD_COMMENT'
export const DELETE_COMMENT = 'POSTS/DELETE_COMMENT'
export const ADD_POST = 'POSTS/ADD_POST'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'
export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/HIDE_ALERT'






